// Generated by gencpp from file car/planner_srvResponse.msg
// DO NOT EDIT!


#ifndef CAR_MESSAGE_PLANNER_SRVRESPONSE_H
#define CAR_MESSAGE_PLANNER_SRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace car
{
template <class ContainerAllocator>
struct planner_srvResponse_
{
  typedef planner_srvResponse_<ContainerAllocator> Type;

  planner_srvResponse_()
    : path(0)  {
    }
  planner_srvResponse_(const ContainerAllocator& _alloc)
    : path(0)  {
  (void)_alloc;
    }



   typedef int64_t _path_type;
  _path_type path;





  typedef boost::shared_ptr< ::car::planner_srvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::car::planner_srvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct planner_srvResponse_

typedef ::car::planner_srvResponse_<std::allocator<void> > planner_srvResponse;

typedef boost::shared_ptr< ::car::planner_srvResponse > planner_srvResponsePtr;
typedef boost::shared_ptr< ::car::planner_srvResponse const> planner_srvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::car::planner_srvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::car::planner_srvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::car::planner_srvResponse_<ContainerAllocator1> & lhs, const ::car::planner_srvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.path == rhs.path;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::car::planner_srvResponse_<ContainerAllocator1> & lhs, const ::car::planner_srvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace car

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::car::planner_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::car::planner_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car::planner_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car::planner_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car::planner_srvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car::planner_srvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::car::planner_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5a0021da7e7b2bc0d903fa21ea74c6df";
  }

  static const char* value(const ::car::planner_srvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5a0021da7e7b2bc0ULL;
  static const uint64_t static_value2 = 0xd903fa21ea74c6dfULL;
};

template<class ContainerAllocator>
struct DataType< ::car::planner_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "car/planner_srvResponse";
  }

  static const char* value(const ::car::planner_srvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::car::planner_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 path\n"
"\n"
"\n"
;
  }

  static const char* value(const ::car::planner_srvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::car::planner_srvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct planner_srvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::car::planner_srvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::car::planner_srvResponse_<ContainerAllocator>& v)
  {
    s << indent << "path: ";
    Printer<int64_t>::stream(s, indent + "  ", v.path);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAR_MESSAGE_PLANNER_SRVRESPONSE_H
