// Generated by gencpp from file car/planner_srvRequest.msg
// DO NOT EDIT!


#ifndef CAR_MESSAGE_PLANNER_SRVREQUEST_H
#define CAR_MESSAGE_PLANNER_SRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace car
{
template <class ContainerAllocator>
struct planner_srvRequest_
{
  typedef planner_srvRequest_<ContainerAllocator> Type;

  planner_srvRequest_()
    : start(0)
    , end(0)  {
    }
  planner_srvRequest_(const ContainerAllocator& _alloc)
    : start(0)
    , end(0)  {
  (void)_alloc;
    }



   typedef int64_t _start_type;
  _start_type start;

   typedef int64_t _end_type;
  _end_type end;





  typedef boost::shared_ptr< ::car::planner_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::car::planner_srvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct planner_srvRequest_

typedef ::car::planner_srvRequest_<std::allocator<void> > planner_srvRequest;

typedef boost::shared_ptr< ::car::planner_srvRequest > planner_srvRequestPtr;
typedef boost::shared_ptr< ::car::planner_srvRequest const> planner_srvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::car::planner_srvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::car::planner_srvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::car::planner_srvRequest_<ContainerAllocator1> & lhs, const ::car::planner_srvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.start == rhs.start &&
    lhs.end == rhs.end;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::car::planner_srvRequest_<ContainerAllocator1> & lhs, const ::car::planner_srvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace car

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::car::planner_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::car::planner_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car::planner_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car::planner_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car::planner_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car::planner_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::car::planner_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d05166f308d494a305f8625733dd9f66";
  }

  static const char* value(const ::car::planner_srvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd05166f308d494a3ULL;
  static const uint64_t static_value2 = 0x05f8625733dd9f66ULL;
};

template<class ContainerAllocator>
struct DataType< ::car::planner_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "car/planner_srvRequest";
  }

  static const char* value(const ::car::planner_srvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::car::planner_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 start\n"
"int64 end\n"
;
  }

  static const char* value(const ::car::planner_srvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::car::planner_srvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start);
      stream.next(m.end);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct planner_srvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::car::planner_srvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::car::planner_srvRequest_<ContainerAllocator>& v)
  {
    s << indent << "start: ";
    Printer<int64_t>::stream(s, indent + "  ", v.start);
    s << indent << "end: ";
    Printer<int64_t>::stream(s, indent + "  ", v.end);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAR_MESSAGE_PLANNER_SRVREQUEST_H
