// Generated by gencpp from file car/planner_srv.msg
// DO NOT EDIT!


#ifndef CAR_MESSAGE_PLANNER_SRV_H
#define CAR_MESSAGE_PLANNER_SRV_H

#include <ros/service_traits.h>


#include <car/planner_srvRequest.h>
#include <car/planner_srvResponse.h>


namespace car
{

struct planner_srv
{

typedef planner_srvRequest Request;
typedef planner_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct planner_srv
} // namespace car


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::car::planner_srv > {
  static const char* value()
  {
    return "1d89cdb41487474b11205506e2f1ce37";
  }

  static const char* value(const ::car::planner_srv&) { return value(); }
};

template<>
struct DataType< ::car::planner_srv > {
  static const char* value()
  {
    return "car/planner_srv";
  }

  static const char* value(const ::car::planner_srv&) { return value(); }
};


// service_traits::MD5Sum< ::car::planner_srvRequest> should match
// service_traits::MD5Sum< ::car::planner_srv >
template<>
struct MD5Sum< ::car::planner_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::car::planner_srv >::value();
  }
  static const char* value(const ::car::planner_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::car::planner_srvRequest> should match
// service_traits::DataType< ::car::planner_srv >
template<>
struct DataType< ::car::planner_srvRequest>
{
  static const char* value()
  {
    return DataType< ::car::planner_srv >::value();
  }
  static const char* value(const ::car::planner_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::car::planner_srvResponse> should match
// service_traits::MD5Sum< ::car::planner_srv >
template<>
struct MD5Sum< ::car::planner_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::car::planner_srv >::value();
  }
  static const char* value(const ::car::planner_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::car::planner_srvResponse> should match
// service_traits::DataType< ::car::planner_srv >
template<>
struct DataType< ::car::planner_srvResponse>
{
  static const char* value()
  {
    return DataType< ::car::planner_srv >::value();
  }
  static const char* value(const ::car::planner_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAR_MESSAGE_PLANNER_SRV_H
